### PR TITLE
# This creates a dynamic dashboard page.

### LINKED ISSUE #2: # This creates personalized recommendations and links.
### Given I have selected my profile type,
*When I* access the dashboard,
*Then I* should see personalized recommendations and links based on my profile type.

### PR DESCRIPTION
**Pull request by EhsanAsh**
## Overview

>The goal of this pull request is to enhance the user experience for newcomers to the GTA by providing personalized recommendations and links on their dashboard. These recommendations are dynamically generated based on the user's selected profile type.

>This pull request aims to implement personalized recommendations and links on the user dashboard for newcomers to the GTA. By adding this feature, we provide valuable, profile-specific information that can aid in a smoother transition and quicker adaptation to the new environment.

## Changes Made

Added a new component that fetches user data based on the selected profile type.
Used local storage to store and receive data.
Defined functions and event listener to create and display recommendations dynamically based on the selected profile type.
Styled by using Materialize CSS library and the Custome CSS.

## How to Test
Log in to the application.
Navigate to the dashboard.
Verify that recommendations and links are personalized based on the selected profile type.
Run unit tests to confirm that the feature meets the acceptance criteria.

### CODE REVIEW

**Comment by EhsanAsh** [comment]
This branch has merge conflicts and should be merged with extra cautious

**Comment by EhsanAsh** [comment]
All merge conflicts has been resolved

**Review by KitSarmiento — APPROVED** [review]
I checked and everything seems good and neat. I run the application and its working properly. Thanks.

**Comment by KitSarmiento** [comment]
The file is good and responsive. Thank you for doing this.

**Pull request merged**
